# DATA GATHERING

In [3]:
import pandas as pd
import numpy as np

### Import data from CSV Files

In [4]:
#opening a local csv file:

df = pd.read_csv('datasets/batter.csv')
df.sample(5)

          batter  runs        avg  strike_rate
6       CH Gayle  4997  39.658730   142.121729
243      P Dogra   127  11.545455    90.070922
4       SK Raina  5536  32.374269   132.535312
317   WD Parnell    63   7.000000    78.750000
372  S Sreesanth    34   8.500000    59.649123

In [5]:
#opening a csv file from url:

import requests
from io import StringIO

url = 'https://raw.githubusercontent.com/amrsaeedhosny/countries/main/countries.csv'
req = requests.get(url)
data = StringIO(req.text)

pd.read_csv(data)

          English Name      Arabic Name Alpha-2 Code Alpha-3 Code  Phone Code
0          Afghanistan        أفغانستان           AF          AFG          93
1        Åland Islands       جزر أولاند           AX          ALA         358
2              Albania          ألبانيا           AL          ALB         355
3              Algeria          الجزائر           DZ          DZA         213
4       American Samoa  ساموا الأمريكية           AS          ASM         684
..                 ...              ...          ...          ...         ...
245  Wallis and Futuna    واليس وفوتونا           WF          WLF         681
246     Western Sahara  الصحراء الغربية           EH          ESH         212
247              Yemen            اليمن           YE          YEM         967
248             Zambia           زامبيا           ZM          ZMB         260
249           Zimbabwe         زيمبابوي           ZW          ZWE         263

[250 rows x 5 columns]

In [6]:
#or pandas can directly read from url:

url = 'https://raw.githubusercontent.com/amrsaeedhosny/countries/main/countries.csv'

df = pd.read_csv(url)
df.head()

     English Name      Arabic Name Alpha-2 Code Alpha-3 Code  Phone Code
0     Afghanistan        أفغانستان           AF          AFG          93
1   Åland Islands       جزر أولاند           AX          ALA         358
2         Albania          ألبانيا           AL          ALB         355
3         Algeria          الجزائر           DZ          DZA         213
4  American Samoa  ساموا الأمريكية           AS          ASM         684

In [7]:
#tsv file dataset (sep parameter):

tsv = pd.read_csv('datasets/Employee Dataset - TSV.txt', sep='\t')
tsv

,Employee Name,Age,Last Working Day,Department,Education,Gender,Marital Status,Monthly Income,Years of Experience,Percent Salary Hike,Performance Rating
0,Jitesh,41,31-12-9999,Training,Masters,Male,Single,5993,8,11,3
1,Sanjit,49,31-12-9999,Sales,Masters,Male,Married,5130,1,23,4
2,John,37,31-12-9999,R&D,Doctorate,Male,Single,2090,6,15,3
3,Sandra,33,31-12-9999,Software Development,Undergraduate,Female,Married,2909,1,11,3
4,Madhu,27,31-12-9999,R&D,Masters,Male,Married,3468,9,12,3
5,Robert,32,31-12-9999,R&D,Masters,Male,Single,3068,0,13,3
6,Megan,59,31-12-9999,Software Development,Masters,Female,Married,2670,4,20,4
7,Matt,30,31-12-9999,R&D,Doctorate,Male,Divorced,2693,1,22,4
8,Will,38,01-03-2012,R&D,Doctorate,Male,Single,9526,0,21,4
9,George,36,31-12-9999,Software Development,Masters,NaN,Married,5237,6,13,3
10,Adam,35,31-12-9999,Software Development,Masters,Male,Married,2426,0,13,3
11,Adam,35,31-12-9999,Software Development,Masters,Male,Married,2426,0,13,3
12,Adam,35,31-12-9999,Software Development,Masters,Male,Married,2426,0,13,3
13,Emma,29,31-12-9999,Software Development,Undergraduate,Female,Single,4193,0,12,3
14,Vin,31,31-12-9999,Software Development,Undergraduate,Male,NaN,2911,1,17,3
15,Richard,34,31-12-9999,Software Development,Undergraduate,Male,Divorced,2661,0,11,3
16,Clint,28,31-12-9999,Software Development,Undergraduate,Male,Single,2028,5,14,3
17,Kate,29,31-12-9999,Software Development,Undergraduate,Female,NaN,9980,1,11,3
18,Morgan,32,31-12-9999,Software Development,Undergraduate,Male,Divorced,3298,0,12,3
19,Mel,22,01-06-2014,Software Development,Masters,Male,Divorced,2935,1,13,3
20,Nicole,53,31-12-9999,Sales,Masters,Female,Married,15427,2,16,3
21,Angelina,38,31-12-9999,R&D,Doctorate,Female,Single,3944,5,11,3
22,Katherine,24,31-12-9999,Development,Masters,Female,Divorced,4011,0,18,3
23,Sean,36,31-12-9999,Sales,Masters,Male,Single,3407,7,23,4
24,Stella,34,31-12-9999,R&D,Doctorate,Female,Single,11994,0,11,3

In [8]:
vk = pd.read_csv('datasets/vk.csv')
vk

     match_id  batsman_runs
0          12            62
1          17            28
2          20            64
3          27             0
4          30            10
..        ...           ...
136       624            75
137       626           113
138       632            54
139       633             0
140       636            54

[141 rows x 2 columns]

In [9]:
#Index_col parameter:

vk = pd.read_csv('datasets/vk.csv', index_col='match_id')
vk

          batsman_runs
match_id
12                  62
17                  28
20                  64
27                   0
30                  10
...                ...
624                 75
626                113
632                 54
633                  0
636                 54

[141 rows x 1 columns]

In [10]:
pd.read_csv('datasets/aug_train.csv', index_col = 'enrollee_id')

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [11]:
# use_cols parameter:

pd.read_csv('datasets/aug_train.csv', usecols=['enrollee_id', 'gender', 'education_level'])

       enrollee_id gender education_level
0             8949   Male        Graduate
1            29725   Male        Graduate
2            11561    NaN        Graduate
3            33241    NaN        Graduate
4              666   Male         Masters
...            ...    ...             ...
19153         7386   Male        Graduate
19154        31398   Male        Graduate
19155        24576   Male        Graduate
19156         5756   Male     High School
19157        23834    NaN  Primary School

[19158 rows x 3 columns]

In [12]:
#skiprows/nrows parameter:

pd.read_csv('datasets/aug_train.csv', skiprows = [3,4])

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
3,21651,city_176,0.764,NaN,Has relevent experience,Part time course,Graduate,STEM,11,NaN,NaN,1,24,1.0
4,28806,city_160,0.920,Male,Has relevent experience,no_enrollment,High School,NaN,5,50-99,Funded Startup,1,24,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19151,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19152,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19153,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19154,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19155,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [13]:
pd.read_csv('datasets/aug_train.csv', nrows = 100)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,12081,city_65,0.802,Male,Has relevent experience,Full time course,Graduate,STEM,9,50-99,Pvt Ltd,1,33,0.0
96,7364,city_160,0.920,NaN,No relevent experience,Full time course,High School,NaN,2,100-500,Pvt Ltd,1,142,0.0
97,11184,city_74,0.579,NaN,No relevent experience,Full time course,Graduate,STEM,2,100-500,Pvt Ltd,1,34,0.0
98,7016,city_65,0.802,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,50-99,Pvt Ltd,2,14,1.0
99,8695,city_11,0.550,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,10/49,Pvt Ltd,2,27,1.0

In [14]:
#encoding parameter:
pd.read_csv('datasets/zomato.csv', encoding='latin-1')

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

In [15]:
#dtypes parameter:
pd.read_csv('datasets/aug_train.csv', dtype={'target':int})

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1
19154,31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1
19155,24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0
19156,5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0

In [16]:
#handling dates:
pd.read_csv('datasets/IPL Matches 2008-2020.csv', parse_dates = ['date']).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    datetime64[ns]
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(13)
memory usage: 108.5+ KB

In [17]:
pd.read_csv('datasets/parse_date.csv', parse_dates=[['day','month', 'date', 'year']])

C:\Users\shubh\AppData\Local\Temp\ipykernel_13032\3695199806.py:1: FutureWarning: Support for nested sequences for 'parse_dates' in pd.read_csv is deprecated. Combine the desired columns with pd.to_datetime after parsing instead.
  pd.read_csv('datasets/parse_date.csv', parse_dates=[['day','month', 'date', 'year']])

    day_month_date_year      name
0  Fri November 18 2004   shubham
1  Sat November 21 2005  konangel
2  Sun February 29 2005    Chesta
3     Mon March 10 2006     Daizy

In [18]:
#converters:

def rename(name):
    if name == 'Royal Challengers Bangalore':
        return 'RCB'
    else:
        return name
    
pd.read_csv('datasets/IPL Matches 2008-2020.csv', converters = {'team1' : rename})

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,RCB,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,RCB,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [19]:
#na_values parameter:
pd.read_csv('datasets/aug_train.csv', na_values=['Male'])

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,NaN,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,NaN,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,NaN,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,NaN,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

In [20]:
#loading a huge dataset in chunks:

dfs = pd.read_csv('datasets/aug_train.csv', chunksize=5000)

In [21]:
for chunks in dfs:
    print(chunks.shape)

(5000, 14)
(5000, 14)
(5000, 14)
(4158, 14)

### Excel Format Dataset:

In [22]:
pd.read_excel('datasets/bestsellers-with-categories.xlsx')

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

### Reading text files:

In [23]:
#importing data:

pd.read_csv('datasets/Employee Dataset - TSV.txt', sep='\t')

,Employee Name,Age,Last Working Day,Department,Education,Gender,Marital Status,Monthly Income,Years of Experience,Percent Salary Hike,Performance Rating
0,Jitesh,41,31-12-9999,Training,Masters,Male,Single,5993,8,11,3
1,Sanjit,49,31-12-9999,Sales,Masters,Male,Married,5130,1,23,4
2,John,37,31-12-9999,R&D,Doctorate,Male,Single,2090,6,15,3
3,Sandra,33,31-12-9999,Software Development,Undergraduate,Female,Married,2909,1,11,3
4,Madhu,27,31-12-9999,R&D,Masters,Male,Married,3468,9,12,3
5,Robert,32,31-12-9999,R&D,Masters,Male,Single,3068,0,13,3
6,Megan,59,31-12-9999,Software Development,Masters,Female,Married,2670,4,20,4
7,Matt,30,31-12-9999,R&D,Doctorate,Male,Divorced,2693,1,22,4
8,Will,38,01-03-2012,R&D,Doctorate,Male,Single,9526,0,21,4
9,George,36,31-12-9999,Software Development,Masters,NaN,Married,5237,6,13,3
10,Adam,35,31-12-9999,Software Development,Masters,Male,Married,2426,0,13,3
11,Adam,35,31-12-9999,Software Development,Masters,Male,Married,2426,0,13,3
12,Adam,35,31-12-9999,Software Development,Masters,Male,Married,2426,0,13,3
13,Emma,29,31-12-9999,Software Development,Undergraduate,Female,Single,4193,0,12,3
14,Vin,31,31-12-9999,Software Development,Undergraduate,Male,NaN,2911,1,17,3
15,Richard,34,31-12-9999,Software Development,Undergraduate,Male,Divorced,2661,0,11,3
16,Clint,28,31-12-9999,Software Development,Undergraduate,Male,Single,2028,5,14,3
17,Kate,29,31-12-9999,Software Development,Undergraduate,Female,NaN,9980,1,11,3
18,Morgan,32,31-12-9999,Software Development,Undergraduate,Male,Divorced,3298,0,12,3
19,Mel,22,01-06-2014,Software Development,Masters,Male,Divorced,2935,1,13,3
20,Nicole,53,31-12-9999,Sales,Masters,Female,Married,15427,2,16,3
21,Angelina,38,31-12-9999,R&D,Doctorate,Female,Single,3944,5,11,3
22,Katherine,24,31-12-9999,Development,Masters,Female,Divorced,4011,0,18,3
23,Sean,36,31-12-9999,Sales,Masters,Male,Single,3407,7,23,4
24,Stella,34,31-12-9999,R&D,Doctorate,Female,Single,11994,0,11,3

## JSON/SQL Dataset:

### JSON Format Dataset:

In [25]:
pd.read_json('datasets/train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

### SQL Dataset:

In [28]:
import mysql.connector

In [30]:
conn = mysql.connector.connect(host='localhost', user='root', password='', database='world')

In [32]:
pd.read_sql_query('SELECT * FROM city', conn)

C:\Users\shubh\AppData\Local\Temp\ipykernel_13032\929584838.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query('SELECT * FROM city', conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]