# MultiIndex Series & DataFrames

In [1]:
import numpy as np
import pandas as pd

In [4]:
#Series with multiindex:

index_val = [('cse',2019), ('cse',2020), ('cse',2021), ('cse', 2022), ('ece',2019), ('ece',2020), ('ece',2021), ('ece',2022)]
a = pd.Series([1,2,3,4,5,6,7,8], index=index_val)

a

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [5]:
a[('cse',2022)]

np.int64(4)

### Creation of multiindex object:

In [6]:
#1.

multiindex = pd.MultiIndex.from_tuples(index_val)
multiindex

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [7]:
multiindex.levels

FrozenList([['cse', 'ece'], [2019, 2020, 2021, 2022]])

In [8]:
multiindex.levels[0]

Index(['cse', 'ece'], dtype='object')

In [10]:
multiindex.levels[1]

Index([2019, 2020, 2021, 2022], dtype='int64')

In [14]:
#2. 

pd.MultiIndex.from_product([['cse','ece'], [2019,2020,2021,2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [18]:
s = pd.Series([1,2,3,4,5,6,7,8], index = multiindex)
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [19]:
s['cse']

2019    1
2020    2
2021    3
2022    4
dtype: int64

In [20]:
s['ece',2020]

np.int64(6)

In [25]:
temp = s.unstack()
temp

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

In [26]:
type(temp)

pandas.core.frame.DataFrame

In [27]:
temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

## MultiIndex DataFrames

In [55]:
branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
    ],

    index = multiindex,
    columns = ['avgpackage', 'students']
)

branch_df1

          avgpackage  students
cse 2019           1         2
    2020           3         4
    2021           5         6
    2022           7         8
ece 2019           9        10
    2020          11        12
    2021          13        14
    2022          15        16

In [56]:
branch_df1.loc['cse']

      avgpackage  students
2019           1         2
2020           3         4
2021           5         6
2022           7         8

In [57]:
branch_df1['avgpackage']

cse  2019     1
     2020     3
     2021     5
     2022     7
ece  2019     9
     2020    11
     2021    13
     2022    15
Name: avgpackage, dtype: int64

In [58]:
branch_df1.loc['cse',2019]['avgpackage']

np.int64(1)

In [59]:
branch_df2 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,9],
        [5,6,0,0],
        [7,8,0,0],
    ],
    index = [2019,2020,2021,2022],
    columns = pd.MultiIndex.from_product([ ['delhi','mumbai'], ['avg_package','students']])
)

branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        9
2021           5        6           0        0
2022           7        8           0        0

In [60]:
branch_df2['mumbai']

      avg_package  students
2019            0         0
2020            0         9
2021            0         0
2022            0         0

In [61]:
branch_df2['delhi']['avg_package']

2019    1
2020    3
2021    5
2022    7
Name: avg_package, dtype: int64

In [62]:
branch_df2.loc[2021]

delhi   avg_package    5
        students       6
mumbai  avg_package    0
        students       0
Name: 2021, dtype: int64

In [63]:
branch_df3 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0],
        [15,16,0,0]
    ],
    index = pd.MultiIndex.from_product([ ['cse','ece'], [2019,2020,2021,2022]]),
    columns = pd.MultiIndex.from_product([ ['delhi','mumbai'], ['avg_package','students'] ])
)

branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

## Stacking and Unstacking

In [66]:
branch_df1

          avgpackage  students
cse 2019           1         2
    2020           3         4
    2021           5         6
    2022           7         8
ece 2019           9        10
    2020          11        12
    2021          13        14
    2022          15        16

In [70]:
branch_df1.unstack()

    avgpackage                students
          2019 2020 2021 2022     2019 2020 2021 2022
cse          1    3    5    7        2    4    6    8
ece          9   11   13   15       10   12   14   16

In [72]:
branch_df1.unstack().unstack()

avgpackage  2019  cse     1
                  ece     9
            2020  cse     3
                  ece    11
            2021  cse     5
                  ece    13
            2022  cse     7
                  ece    15
students    2019  cse     2
                  ece    10
            2020  cse     4
                  ece    12
            2021  cse     6
                  ece    14
            2022  cse     8
                  ece    16
dtype: int64

In [74]:
branch_df1.unstack().stack()

C:\Users\shubh\AppData\Local\Temp\ipykernel_1612\1991893145.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df1.unstack().stack()

          avgpackage  students
cse 2019           1         2
    2020           3         4
    2021           5         6
    2022           7         8
ece 2019           9        10
    2020          11        12
    2021          13        14
    2022          15        16

In [75]:
branch_df1.unstack().stack().stack()

C:\Users\shubh\AppData\Local\Temp\ipykernel_1612\2994828746.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df1.unstack().stack().stack()

cse  2019  avgpackage     1
           students       2
     2020  avgpackage     3
           students       4
     2021  avgpackage     5
           students       6
     2022  avgpackage     7
           students       8
ece  2019  avgpackage     9
           students      10
     2020  avgpackage    11
           students      12
     2021  avgpackage    13
           students      14
     2022  avgpackage    15
           students      16
dtype: int64

In [76]:
branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        9
2021           5        6           0        0
2022           7        8           0        0

In [77]:
branch_df2.unstack()

delhi   avg_package  2019    1
                     2020    3
                     2021    5
                     2022    7
        students     2019    2
                     2020    4
                     2021    6
                     2022    8
mumbai  avg_package  2019    0
                     2020    0
                     2021    0
                     2022    0
        students     2019    0
                     2020    9
                     2021    0
                     2022    0
dtype: int64

In [78]:
branch_df2.stack()

C:\Users\shubh\AppData\Local\Temp\ipykernel_1612\3132666484.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df2.stack()

                  delhi  mumbai
2019 avg_package      1       0
     students         2       0
2020 avg_package      3       0
     students         4       9
2021 avg_package      5       0
     students         6       0
2022 avg_package      7       0
     students         8       0

In [81]:
branch_df2.stack().stack()

C:\Users\shubh\AppData\Local\Temp\ipykernel_1612\2534568903.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df2.stack().stack()

2019  avg_package  delhi     1
                   mumbai    0
      students     delhi     2
                   mumbai    0
2020  avg_package  delhi     3
                   mumbai    0
      students     delhi     4
                   mumbai    9
2021  avg_package  delhi     5
                   mumbai    0
      students     delhi     6
                   mumbai    0
2022  avg_package  delhi     7
                   mumbai    0
      students     delhi     8
                   mumbai    0
dtype: int64

In [82]:
branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [83]:
branch_df3.unstack()

          delhi                                             mumbai            \
    avg_package                students                avg_package
           2019 2020 2021 2022     2019 2020 2021 2022        2019 2020 2021
cse           1    3    5    7        2    4    6    8           0    0    0
ece           9   11   13   15       10   12   14   16           0    0    0


         students
    2022     2019 2020 2021 2022
cse    0        0    0    0    0
ece    0        0    0    0    0

In [85]:
branch_df3.unstack().unstack()

delhi   avg_package  2019  cse     1
                           ece     9
                     2020  cse     3
                           ece    11
                     2021  cse     5
                           ece    13
                     2022  cse     7
                           ece    15
        students     2019  cse     2
                           ece    10
                     2020  cse     4
                           ece    12
                     2021  cse     6
                           ece    14
                     2022  cse     8
                           ece    16
mumbai  avg_package  2019  cse     0
                           ece     0
                     2020  cse     0
                           ece     0
                     2021  cse     0
                           ece     0
                     2022  cse     0
                           ece     0
        students     2019  cse     0
                           ece     0
                     2020  cse     0
                           ece     0
                     2021  cse     0
                           ece     0
                     2022  cse     0
                           ece     0
dtype: int64

In [86]:
branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [87]:
branch_df3.stack()

C:\Users\shubh\AppData\Local\Temp\ipykernel_1612\4148153360.py:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  branch_df3.stack()

                      delhi  mumbai
cse 2019 avg_package      1       0
         students         2       0
    2020 avg_package      3       0
         students         4       0
    2021 avg_package      5       0
         students         6       0
    2022 avg_package      7       0
         students         8       0
ece 2019 avg_package      9       0
         students        10       0
    2020 avg_package     11       0
         students        12       0
    2021 avg_package     13       0
         students        14       0
    2022 avg_package     15       0
         students        16       0

## Working with multiindex dataframes

In [88]:
branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [90]:
branch_df3.head(1)

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0

In [92]:
branch_df3.shape

(8, 4)

In [93]:
branch_df3.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 8 entries, ('cse', np.int64(2019)) to ('ece', np.int64(2022))
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (delhi, avg_package)   8 non-null      int64
 1   (delhi, students)      8 non-null      int64
 2   (mumbai, avg_package)  8 non-null      int64
 3   (mumbai, students)     8 non-null      int64
dtypes: int64(4)
memory usage: 632.0+ bytes

In [97]:
branch_df3.duplicated()

cse  2019    False
     2020    False
     2021    False
     2022    False
ece  2019    False
     2020    False
     2021    False
     2022    False
dtype: bool

In [98]:
branch_df3.isnull()

               delhi               mumbai
         avg_package students avg_package students
cse 2019       False    False       False    False
    2020       False    False       False    False
    2021       False    False       False    False
    2022       False    False       False    False
ece 2019       False    False       False    False
    2020       False    False       False    False
    2021       False    False       False    False
    2022       False    False       False    False

In [100]:
branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

In [102]:
#extracting rows single:
branch_df3.loc[('ece', 2019)]

delhi   avg_package     9
        students       10
mumbai  avg_package     0
        students        0
Name: (ece, 2019), dtype: int64

In [104]:
#extracting multiple rows:
branch_df3.loc[('cse',2019):('ece',2020):2]

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2021           5        6           0        0
ece 2019           9       10           0        0

In [106]:
#using iloc:

branch_df3.iloc[4]

delhi   avg_package     9
        students       10
mumbai  avg_package     0
        students        0
Name: (ece, 2019), dtype: int64

In [107]:
branch_df3.iloc[0:5:2]

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2021           5        6           0        0
ece 2019           9       10           0        0