# MultiIndex Series & DataFrames

In [1]:
import numpy as np
import pandas as pd

In [4]:
#Series with multiindex:

index_val = [('cse',2019), ('cse',2020), ('cse',2021), ('cse', 2022), ('ece',2019), ('ece',2020), ('ece',2021), ('ece',2022)]
a = pd.Series([1,2,3,4,5,6,7,8], index=index_val)

a

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [5]:
a[('cse',2022)]

np.int64(4)

### Creation of multiindex object:

In [6]:
#1.

multiindex = pd.MultiIndex.from_tuples(index_val)
multiindex

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [7]:
multiindex.levels

FrozenList([['cse', 'ece'], [2019, 2020, 2021, 2022]])

In [8]:
multiindex.levels[0]

Index(['cse', 'ece'], dtype='object')

In [10]:
multiindex.levels[1]

Index([2019, 2020, 2021, 2022], dtype='int64')

In [14]:
#2. 

pd.MultiIndex.from_product([['cse','ece'], [2019,2020,2021,2022]])

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [18]:
s = pd.Series([1,2,3,4,5,6,7,8], index = multiindex)
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [19]:
s['cse']

2019    1
2020    2
2021    3
2022    4
dtype: int64

In [20]:
s['ece',2020]

np.int64(6)

In [25]:
temp = s.unstack()
temp

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

In [26]:
type(temp)

pandas.core.frame.DataFrame

In [27]:
temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

## MultiIndex DataFrames

In [31]:
branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
    ],

    index = multiindex,
    columns = ['avgpackage', 'students']
)

branch_df1

          avgpackage  students
cse 2019           1         2
    2020           3         4
    2021           5         6
    2022           7         8
ece 2019           9        10
    2020          11        12
    2021          13        14
    2022          15        16

In [32]:
branch_df1.loc['cse']

      avgpackage  students
2019           1         2
2020           3         4
2021           5         6
2022           7         8

In [36]:
branch_df1['avgpackage']

cse  2019     1
     2020     3
     2021     5
     2022     7
ece  2019     9
     2020    11
     2021    13
     2022    15
Name: avgpackage, dtype: int64

In [39]:
branch_df1.loc['cse',2019]['avgpackage']

np.int64(1)

In [43]:
branch_df2 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,9],
        [5,6,0,0],
        [7,8,0,0],
    ],
    index = [2019,2020,2021,2022],
    columns = pd.MultiIndex.from_product([ ['delhi','mumbai'], ['avg_package','students']])
)

branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        9
2021           5        6           0        0
2022           7        8           0        0

In [44]:
branch_df2['mumbai']

      avg_package  students
2019            0         0
2020            0         9
2021            0         0
2022            0         0

In [46]:
branch_df2['delhi']['avg_package']

2019    1
2020    3
2021    5
2022    7
Name: avg_package, dtype: int64

In [48]:
branch_df2.loc[2021]

delhi   avg_package    5
        students       6
mumbai  avg_package    0
        students       0
Name: 2021, dtype: int64