## Pivot Table

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
#avf total bill gender wise:

df.groupby('sex')[['total_bill']].mean()

C:\Users\shubh\AppData\Local\Temp\ipykernel_14124\2699088291.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('sex')[['total_bill']].mean()

        total_bill
sex
Male     20.744076
Female   18.056897

In [4]:
#avg bill paid by somker males and smoker females:
df.groupby(['sex', 'smoker'])[['total_bill']].mean().unstack()

C:\Users\shubh\AppData\Local\Temp\ipykernel_14124\624953483.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['sex', 'smoker'])[['total_bill']].mean().unstack()

       total_bill
smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [5]:
#using pivot:

df.pivot_table(index = 'sex', columns = 'smoker', values = 'total_bill')

C:\Users\shubh\AppData\Local\Temp\ipykernel_14124\2574518608.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index = 'sex', columns = 'smoker', values = 'total_bill')

smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [6]:
df.pivot_table(index='sex', columns='smoker', values='total_bill', aggfunc='count')

C:\Users\shubh\AppData\Local\Temp\ipykernel_14124\2176768182.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns='smoker', values='total_bill', aggfunc='count')

smoker  Yes  No
sex
Male     60  97
Female   33  54

In [8]:
df.pivot_table(index='sex', columns='smoker', aggfunc='count')

C:\Users\shubh\AppData\Local\Temp\ipykernel_14124\3284742983.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns='smoker', aggfunc='count')

       day     size     time     tip     total_bill
smoker Yes  No  Yes  No  Yes  No Yes  No        Yes  No
sex
Male    60  97   60  97   60  97  60  97         60  97
Female  33  54   33  54   33  54  33  54         33  54

In [10]:
#multidimensional:
df.pivot_table(index=['sex', 'smoker'], columns=['day', 'time'], values='total_bill')

C:\Users\shubh\AppData\Local\Temp\ipykernel_14124\3983692338.py:2: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index=['sex', 'smoker'], columns=['day', 'time'], values='total_bill')

day                 Thur               Fri                Sat        Sun
time               Lunch Dinner      Lunch  Dinner     Dinner     Dinner
sex    smoker
Male   Yes     19.171000    NaN  11.386667  25.892  21.837778  26.141333
       No      18.486500    NaN        NaN  17.475  19.929063  20.403256
Female Yes     19.218571    NaN  13.260000  12.200  20.266667  16.540000
       No      15.899167  18.78  15.980000  22.750  19.003846  20.824286

In [13]:
df.pivot_table(index=['sex','smoker'], columns=['day', 'time'], aggfunc={'size':'mean', 'tip':'max', 'total_bill':'sum'})

C:\Users\shubh\AppData\Local\Temp\ipykernel_14124\2475215802.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index=['sex','smoker'], columns=['day', 'time'], aggfunc={'size':'mean', 'tip':'max', 'total_bill':'sum'})

                   size                                               tip  \
day                Thur              Fri              Sat       Sun  Thur
time              Lunch Dinner     Lunch Dinner    Dinner    Dinner Lunch
sex    smoker
Male   Yes     2.300000    NaN  1.666667    2.4  2.629630  2.600000  5.00
       No      2.500000    NaN       NaN    2.0  2.656250  2.883721  6.70
Female Yes     2.428571    NaN  2.000000    2.0  2.200000  2.500000  5.00
       No      2.500000    2.0  3.000000    2.0  2.307692  3.071429  5.17

                                                total_bill                \
day                    Fri           Sat    Sun       Thur           Fri
time          Dinner Lunch Dinner Dinner Dinner      Lunch Dinner  Lunch
sex    smoker
Male   Yes       NaN  2.20   4.73  10.00    6.5     191.71   0.00  34.16
       No        NaN   NaN   3.50   9.00    6.0     369.73   0.00   0.00
Female Yes       NaN  3.48   4.30   6.50    4.0     134.53   0.00  39.78
       No        3.0  3.00   3.25   4.67    5.2     381.58  18.78  15.98


day                     Sat           Sun
time           Dinner Lunch  Dinner Lunch  Dinner
sex    smoker
Male   Yes     129.46   0.0  589.62   0.0  392.12
       No       34.95   0.0  637.73   0.0  877.34
Female Yes      48.80   0.0  304.00   0.0   66.16
       No       22.75   0.0  247.05   0.0  291.54

In [16]:
#margins:

df.pivot_table(index='sex', columns='smoker', values='total_bill', aggfunc='sum', margins=True)

C:\Users\shubh\AppData\Local\Temp\ipykernel_14124\2654975135.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns='smoker', values='total_bill', aggfunc='sum', margins=True)

smoker      Yes       No      All
sex
Male    1337.07  1919.75  3256.82
Female   593.27   977.68  1570.95
All     1930.34  2897.43  4827.77

In [26]:
#plotting graphs:
dfe= pd.read_csv('datasets/expense_data.csv').squeeze()
dfe

,Date,Account,Category,Subcategory,Note,INR,Income/Expense,Note.1,Amount,Currency,Account.1
0,3/2/2022 10:11,CUB - online payment,Food,NaN,Brownie,50.0,Expense,NaN,50.0,INR,50.0
1,3/2/2022 10:11,CUB - online payment,Other,NaN,To lended people,300.0,Expense,NaN,300.0,INR,300.0
2,3/1/2022 19:50,CUB - online payment,Food,NaN,Dinner,78.0,Expense,NaN,78.0,INR,78.0
3,3/1/2022 18:56,CUB - online payment,Transportation,NaN,Metro,30.0,Expense,NaN,30.0,INR,30.0
4,3/1/2022 18:22,CUB - online payment,Food,NaN,Snacks,67.0,Expense,NaN,67.0,INR,67.0
...,...,...,...,...,...,...,...,...,...,...,...
272,11/22/2021 14:16,CUB - online payment,Food,NaN,Dinner,90.0,Expense,NaN,90.0,INR,90.0
273,11/22/2021 14:16,CUB - online payment,Food,NaN,Lunch with company,97.0,Expense,NaN,97.0,INR,97.0
274,11/21/2021 17:07,CUB - online payment,Transportation,NaN,Rapido,130.0,Expense,NaN,130.0,INR,130.0
275,11/21/2021 15:50,CUB - online payment,Food,NaN,Lunch,875.0,Expense,NaN,875.0,INR,875.0
276,11/21/2021 13:30,CUB - online payment,Other,NaN,Got from gobi,2000.0,Income,NaN,2000.0,INR,2000.0

In [27]:
dfe['Category'].value_counts()

Category
Food                156
Other                60
Transportation       31
Apparel               7
Household             6
Allowance             6
Social Life           5
Education             1
Salary                1
Self-development      1
Beauty                1
Gift                  1
Petty cash            1
Name: count, dtype: int64

In [28]:
dfe['Date']=pd.to_datetime(dfe['Date'])

In [29]:
dfe

,Date,Account,Category,Subcategory,Note,INR,Income/Expense,Note.1,Amount,Currency,Account.1
0,2022-03-02 10:11:00,CUB - online payment,Food,NaN,Brownie,50.0,Expense,NaN,50.0,INR,50.0
1,2022-03-02 10:11:00,CUB - online payment,Other,NaN,To lended people,300.0,Expense,NaN,300.0,INR,300.0
2,2022-03-01 19:50:00,CUB - online payment,Food,NaN,Dinner,78.0,Expense,NaN,78.0,INR,78.0
3,2022-03-01 18:56:00,CUB - online payment,Transportation,NaN,Metro,30.0,Expense,NaN,30.0,INR,30.0
4,2022-03-01 18:22:00,CUB - online payment,Food,NaN,Snacks,67.0,Expense,NaN,67.0,INR,67.0
...,...,...,...,...,...,...,...,...,...,...,...
272,2021-11-22 14:16:00,CUB - online payment,Food,NaN,Dinner,90.0,Expense,NaN,90.0,INR,90.0
273,2021-11-22 14:16:00,CUB - online payment,Food,NaN,Lunch with company,97.0,Expense,NaN,97.0,INR,97.0
274,2021-11-21 17:07:00,CUB - online payment,Transportation,NaN,Rapido,130.0,Expense,NaN,130.0,INR,130.0
275,2021-11-21 15:50:00,CUB - online payment,Food,NaN,Lunch,875.0,Expense,NaN,875.0,INR,875.0
276,2021-11-21 13:30:00,CUB - online payment,Other,NaN,Got from gobi,2000.0,Income,NaN,2000.0,INR,2000.0

In [34]:
dfe['month']=dfe['Date'].dt.month_name()

In [35]:
dfe.head()

,Date,Account,Category,Subcategory,Note,INR,Income/Expense,Note.1,Amount,Currency,Account.1,month
0,2022-03-02 10:11:00,CUB - online payment,Food,NaN,Brownie,50.0,Expense,NaN,50.0,INR,50.0,March
1,2022-03-02 10:11:00,CUB - online payment,Other,NaN,To lended people,300.0,Expense,NaN,300.0,INR,300.0,March
2,2022-03-01 19:50:00,CUB - online payment,Food,NaN,Dinner,78.0,Expense,NaN,78.0,INR,78.0,March
3,2022-03-01 18:56:00,CUB - online payment,Transportation,NaN,Metro,30.0,Expense,NaN,30.0,INR,30.0,March
4,2022-03-01 18:22:00,CUB - online payment,Food,NaN,Snacks,67.0,Expense,NaN,67.0,INR,67.0,March

In [37]:
dfe.pivot_table(index='month', columns='Category', values='INR', aggfunc=sum)

C:\Users\shubh\AppData\Local\Temp\ipykernel_14124\2830237450.py:1: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  dfe.pivot_table(index='month', columns='Category', values='INR', aggfunc=sum)

Category,Allowance,Apparel,Beauty,Education,Food,Gift,Household,Other,Petty cash,Salary,Self-development,Social Life,Transportation
month,,,,,,,,,,,,,
December,11000.0,2590.0,196.0,NaN,6440.72,NaN,4800.0,1790.0,NaN,NaN,400.0,513.72,914.0
February,NaN,798.0,NaN,NaN,5579.85,NaN,2808.0,20000.0,NaN,NaN,NaN,1800.00,5078.8
January,1000.0,NaN,NaN,1400.0,9112.51,NaN,4580.0,13178.0,NaN,8000.0,NaN,200.00,2850.0
March,NaN,NaN,NaN,NaN,195.00,NaN,NaN,900.0,NaN,NaN,NaN,NaN,30.0
November,2000.0,NaN,NaN,NaN,3174.40,115.0,NaN,2000.0,3.0,NaN,NaN,NaN,331.0