## Pivot Table

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [3]:
#avf total bill gender wise:

df.groupby('sex')[['total_bill']].mean()

C:\Users\shubh\AppData\Local\Temp\ipykernel_14124\2699088291.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('sex')[['total_bill']].mean()

        total_bill
sex
Male     20.744076
Female   18.056897

In [4]:
#avg bill paid by somker males and smoker females:
df.groupby(['sex', 'smoker'])[['total_bill']].mean().unstack()

C:\Users\shubh\AppData\Local\Temp\ipykernel_14124\624953483.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['sex', 'smoker'])[['total_bill']].mean().unstack()

       total_bill
smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [5]:
#using pivot:

df.pivot_table(index = 'sex', columns = 'smoker', values = 'total_bill')

C:\Users\shubh\AppData\Local\Temp\ipykernel_14124\2574518608.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index = 'sex', columns = 'smoker', values = 'total_bill')

smoker        Yes         No
sex
Male    22.284500  19.791237
Female  17.977879  18.105185

In [6]:
df.pivot_table(index='sex', columns='smoker', values='total_bill', aggfunc='count')

C:\Users\shubh\AppData\Local\Temp\ipykernel_14124\2176768182.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns='smoker', values='total_bill', aggfunc='count')

smoker  Yes  No
sex
Male     60  97
Female   33  54

In [8]:
df.pivot_table(index='sex', columns='smoker', aggfunc='count')

C:\Users\shubh\AppData\Local\Temp\ipykernel_14124\3284742983.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='sex', columns='smoker', aggfunc='count')

       day     size     time     tip     total_bill
smoker Yes  No  Yes  No  Yes  No Yes  No        Yes  No
sex
Male    60  97   60  97   60  97  60  97         60  97
Female  33  54   33  54   33  54  33  54         33  54

In [9]:
#multidimensional:
df.pivot_table(index=['sex', 'smaoker'], columns=['day', 'time'], values='total_bill')

KeyError: 'smaoker'